kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: optum-resizable-retained
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
allowVolumeExpansion: true  